name: deploy hasanjoldic.com

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            if cd /root/apps/hasanjoldic.com; then git pull; 
            else git clone git@github.com:hasanjoldic/hasanjoldic.com.git /root/apps/hasanjoldic.com; 
            fi
            echo "@hasanjoldic:registry=https://npm.pkg.github.com/" > .npmrc
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
            git update-index --assume-unchanged .npmrc
            cd /root/apps/hasanjoldic.com && docker-compose up --build --detach
          host: hasanjoldic.com
          username: root
          privateKey: ${{ secrets.HASAN_JOLDIC_COM_PRIVATE_KEY }}
